bn:
  eps: 1.0e-05
  mom: 0.1
cfg_dest: config.yaml
custom_metrics: []
dataset:
  augment_feature: []
  augment_feature_dims:
  - 0
  augment_feature_repr: position
  augment_label: ''
  augment_label_dims: 0
  cache_load: false
  cache_save: false
  dir: ./datasets
  edge_dim: 128
  edge_encoder: false
  edge_encoder_bn: true
  edge_encoder_name: Bond
  edge_message_ratio: 0.8
  edge_negative_sampling_ratio: 1.0
  edge_train_mode: all
  encoder: true
  encoder_bn: true
  encoder_dim: 128
  encoder_name: db
  format: PyG
  label_column: none
  label_table: none
  location: local
  name: Custom,MARKER_LUAD_ESET,
  node_encoder: false
  node_encoder_bn: true
  node_encoder_name: Atom
  remove_feature: false
  resample_disjoint: false
  resample_negative: false
  shuffle_split: true
  split:
  - 0.8
  - 0.2
  split_mode: random
  task: graph
  task_type: classification
  to_undirected: false
  transductive: false
  transform: none
  tu_simple: true
device: auto
example_arg: example
example_group:
  example_arg: example
gnn:
  act: prelu
  agg: add
  att_final_linear: false
  att_final_linear_bn: false
  att_heads: 1
  batchnorm: true
  clear_feature: true
  dim_inner: 59
  dropout: 0.0
  flow: source_to_target
  head: graph
  keep_edge: 0.5
  l2norm: true
  layer_type: generalconv
  layers_mp: 2
  layers_post_mp: 2
  layers_pre_mp: 1
  msg_direction: single
  normalize_adj: false
  self_msg: concat
  skip_every: 1
  stage_type: skipconcat
gpu_mem: false
mem:
  inplace: false
metric_agg: argmax
metric_best: auto
model:
  edge_decoding: dot
  graph_pooling: add
  loss_fun: cross_entropy
  match_upper: true
  size_average: mean
  thresh: 0.5
  type: gnn
num_threads: 6
num_workers: 0
optim:
  base_lr: 0.01
  lr_decay: 0.1
  max_epoch: 200
  momentum: 0.9
  optimizer: adam
  scheduler: cos
  steps:
  - 30
  - 60
  - 90
  weight_decay: 0.0005
out_dir: results/MARKER_LUAD_ESET_grid_MARKER_LUAD_ESET/MARKER_LUAD_ESET-format=PyG-dataset=MARKER_LUAD_ESET-task=graph-trans=False-feature=-label=-l_pre=1-l_mp=2-l_post=2-stage=skipconcat-agg=add
print: both
round: 4
run_dir: results/MARKER_LUAD_ESET_grid_MARKER_LUAD_ESET
seed: 0
share:
  dim_in: 1
  dim_out: 1
  num_splits: 1
tensorboard_agg: true
tensorboard_each_run: false
train:
  auto_resume: false
  batch_size: 10
  ckpt_clean: true
  ckpt_period: 100
  enable_ckpt: true
  epoch_resume: -1
  eval_period: 20
  iter_per_epoch: 32
  mode: standard
  neighbor_sizes:
  - 20
  - 15
  - 10
  - 5
  node_per_graph: 32
  radius: extend
  sample_node: false
  sampler: full_batch
  skip_train_eval: false
  walk_length: 4
val:
  node_per_graph: 32
  radius: extend
  sample_node: false
  sampler: full_batch
view_emb: false

