batch_size : 3         # When training, how many instances should we have at once
eval_period : 20        # After how many training rounds we do an evaluation
layers_pre_mp : 1       # How many layers exist before the message passing phase
layers_mp : 8           # How many rounds of message passing do we do
layers_post_mp : 6      # HOw many layers deep is the neural network after we do all the message passing
dim_inner : 60         # How many neurons are in the hidden layers
max_epoch : 100         # How many epochs we train for
stage_type: skipsum
agg: mean